### ISSUE TITLE
Linked handles

### ISSUE THREAD

**Issue by Dara-K** [topcoder-platform/timeline-wall-api#10]
The handles that appear under the author, should be colored by rating and linked to the member's profile

**Comment by suppermancool** [comment]
@igoroshko the API `GET https://api.topcoder-dev.com/v5/timeline-wall/timelineEvents` only returns the member handle. it must also return `member rating` to show the member's color

**Comment by igoroshko** [comment]
@suppermancool for now let's only set link to profile page

**Comment by suppermancool** [comment]
@igoroshko done in https://github.com/topcoder-platform/community-app/pull/6722

**Comment by Dara-K** [comment]
This one is completed, thank you
