### ISSUE TITLE
Clear post-submission confirmation

### ISSUE THREAD

**Issue by ketzjs09** [topcoder-platform/timeline-wall-api#12]
We need a confirmation post-submission such as 'you photo/video has been submitted and is under review'.

**Comment by igoroshko** [comment]
@ketzjs09 I think we already have it:

![image](https://user-images.githubusercontent.com/15140568/201098029-cd7bac2b-ce21-4b38-b36f-b7e3c6540f88.png)

**Comment by Dara-K** [comment]
Yes we have it @ketzjs09
