### ISSUE TITLE
Feature request - Add 'sort by most recent post date'

### ISSUE THREAD

**Issue by ketzjs09** [topcoder-platform/timeline-wall-api#13]
Would be good to have an additional sort-by option, which shows the most recently posted photos (in addition to the default sort by event date as seen here)

**Comment by igoroshko** [comment]
@ketzjs09  @Dara-K How would the navigation panel work in this case?

**Comment by Dara-K** [comment]
The scope of this application is a timeline wall, the idea is to work that way, not to have it be a sortable list.
