### ISSUE TITLE
Upon clicking on a post, it should open along with the text

### ISSUE THREAD

**Issue by ketzjs09** [topcoder-platform/timeline-wall-api#14]
Right now once I click on a picture, it opens only with the photo or video. Ideally it should open along with the text in the post.

**Comment by igoroshko** [comment]
@Dara-K I think we don't have design for this one.

**Comment by Dara-K** [comment]
@igoroshko  We don't need this to open with the text. It's how it's planned.

**Comment by ketzjs09** [comment]
@Dara-K considering that this has been labelled as invalid, I assume only bug reports and no feature suggestions/requests were expected?

**Comment by igoroshko** [comment]
I'll remove **invalid** label until @Dara-K provides clarification.

**Comment by Dara-K** [comment]
Can we add the tag Feature @igoroshko  ? and count it that way. We can solve just bugs but keep the others for reference for future on new things we can add.

**Comment by Dara-K** [comment]
@ketzjs09 This is something we've discussed with Jessie and Oanh and decided not to do.
