### ISSUE TITLE
Side navigation doesn't work on mobile

### ISSUE THREAD

**Issue by Dara-K** [topcoder-platform/timeline-wall-api#17]
When selecting a different year from the top dropdown, it's still showing all the time the most recent card and doesn't move to the events that corresponds to those years.

**Comment by suppermancool** [comment]
@igoroshko done in https://github.com/topcoder-platform/community-app/pull/6719

**Comment by Dara-K** [comment]
@igoroshko  The issue mentioned was fixed, thank you.
Note: in the default state, we should still see the label written on top as the latest year 2022 as per design https://www.figma.com/proto/6rZMMZwJjLdxvKi3vSVKRO/Timeline-Wall?node-id=3059%3A86969&scaling=scale-down&page-id=2863%3A26781&starting-point-node-id=3059%3A86969

Now it's not showing
![image](https://user-images.githubusercontent.com/25185079/204915415-0d5929b8-8089-4d3e-abb9-bc62f4b75199.png)

**Comment by igoroshko** [comment]
@Dara-K ok, I'll close this one and open a new issue for the default value.
