### ISSUE TITLE
Approvals number should increase automatically

### ISSUE THREAD

**Issue by Dara-K** [topcoder-platform/timeline-wall-api#18]
Approvals number should increase automatically without the admin refreshing the page to see new events added

**Comment by igoroshko** [comment]
@Dara-K do you mean it should continuosly send requests to backend to check for a new events?

Please note when admin adds new event it doesn't need approval, so the count won't change in this case.

**Comment by igoroshko** [comment]
@Dara-K any update on this one?

**Comment by Dara-K** [comment]
@igoroshko  I mean that if a person submits an event and me as an admin I am into admin page, and keep approving things, that new event is not showing on my page unless I refresh the screen.

**Comment by igoroshko** [comment]
@Dara-K we can do that, but it adds a bit more complexity and more network requests that we actually need. And I don't think we are doing it anywhere else on Topcoder website. For example, when a new challenge is posted, users will have to refresh the page to see that.

**Comment by igoroshko** [comment]
Let's do periodical API calls every 5 minutes to get updated list of pending approval events.

**Comment by suppermancool** [comment]
@igoroshko done in https://github.com/topcoder-platform/community-app/pull/6726

**Comment by igoroshko** [comment]
@suppermancool can you please fix the merge confilict?

**Comment by suppermancool** [comment]
@igoroshko done

**Comment by Dara-K** [comment]
This works, thank you both!

Please close this ticket @igoroshko
