### ISSUE TITLE
Image file format validation

### ISSUE THREAD

**Issue by penatrix-tc** [topcoder-platform/timeline-wall-api#21]
-
feel free to remove this issue

**Comment by Dara-K** [comment]
This bug together with the security bugs have been shared directly with Nightwolf 1-1.

**Comment by igoroshko** [comment]
The backend will fail during thumbnail generation in case it is a wrong file, so it is not a big concern, but we can improve that later if needed, so I'll set Low priority for this one.

**Comment by Dara-K** [comment]
@igoroshko  I think this was fixed right? I tried uploading wrong files and it is not working

**Comment by igoroshko** [comment]
yes, I think we can close it, and add enhancements in future if needed.
