### ISSUE TITLE
Attachment text length limit only softly enforced

### ISSUE THREAD

**Issue by penatrix-tc** [topcoder-platform/timeline-wall-api#23]
-
feel free to remove this issue

**Comment by igoroshko** [comment]
@penatrix-tc actually, it is enforced on the backend too, but frontend doesn't handle errors well. And looks like on backend limit is different. I'll also create issue to handle backend errors:

![image](https://user-images.githubusercontent.com/15140568/201099097-f20b2409-ece7-4c8e-bfab-875146ce96e5.png)

**Comment by penatrix-tc** [comment]
That's good! I only had access to the frontend while testing, so I couldn't be sure

**Comment by igoroshko** [comment]
To test this, please right click on the description box and select Inspect, then remove the length attribute from the **textarea** element. This will bypass frontend validation, so you can now enter text into textbox which exceeds 240 chars. Once event is submitted, you should get validation error from backend.

![image](https://user-images.githubusercontent.com/15140568/205025988-78138138-1c8a-411a-b66e-fa4ffbaed2f9.png)

**Comment by Dara-K** [comment]
Thanks for the instructions @igoroshko 
This works! I can see the backend message. Can we change the error message to be red this color #EF476F?  and instead of "CONFIRMATION" write "ERROR"
![image](https://user-images.githubusercontent.com/25185079/205274879-e0d93482-7417-4ef9-a2aa-7899c84ae1b0.png)

**Comment by igoroshko** [comment]
@Dara-K created new ticket for that - #32
