### ISSUE TITLE
Forums link

### ISSUE THREAD

**Issue by Dara-K** [topcoder-platform/timeline-wall-api#25]
Add link to forums as shown in the design here - it's called "DISCUSS ->"
Desktop: https://www.figma.com/file/6rZMMZwJjLdxvKi3vSVKRO/Timeline-Wall?node-id=3047%3A27842 
Mobile: https://www.figma.com/file/6rZMMZwJjLdxvKi3vSVKRO/Timeline-Wall?node-id=3047%3A27842

**Comment by suppermancool** [comment]
@igoroshko done in https://github.com/topcoder-platform/community-app/pull/6721

**Comment by suppermancool** [comment]
@igoroshko look like you forgot to merge the above PR

**Comment by igoroshko** [comment]
@suppermancool yep, thanks! Merged

**Comment by igoroshko** [comment]
@suppermancool sorry, we forgot to include URL link. Can you please update the code to use following link?
https://discussions.topcoder.com/discussion/24281/add-your-memory-to-the-topcoder-timeline-wall

**Comment by suppermancool** [comment]
@igoroshko done in https://github.com/topcoder-platform/community-app/pull/6733

**Comment by igoroshko** [comment]
@suppermancool can we please fix the link color to keep it white even after it was visited?

![image](https://user-images.githubusercontent.com/15140568/203384324-b7f9e61c-9e31-4bee-af52-98faa4d6563c.png)

**Comment by suppermancool** [comment]
@igoroshko done in https://github.com/topcoder-platform/community-app/pull/6736

**Comment by Dara-K** [comment]
This looks good to me, thank you!

**Comment by Dara-K** [comment]
@igoroshko  Please close this ticket
