### ISSUE TITLE
Handle errors from backend properly

### ISSUE THREAD

**Issue by igoroshko** [topcoder-platform/timeline-wall-api#26]
At the moment if backend fails to create an event, the frontend app will still display success message. This should be fixed. We can use same popup for now, but display the error message from the backend.

![image](https://user-images.githubusercontent.com/15140568/201101672-dc9fb6c2-24d9-40fa-8336-9d3e507efa9d.png)

**Comment by suppermancool** [comment]
@igoroshko done in https://github.com/topcoder-platform/community-app/pull/6720

**Comment by igoroshko** [comment]
This can be verified by following steps described in issue #23

**Comment by Dara-K** [comment]
Makes sense and works, thank you! 
Let's close this ticket @igoroshko
