### ISSUE TITLE
Backend should return proper error message in the API response

### ISSUE THREAD

**Issue by igoroshko** [topcoder-platform/timeline-wall-api#27]
Currently backend returns "Internal error..." message, which isn't informative

**Comment by Dara-K** [comment]
@igoroshko  How can this bug be tested?

**Comment by igoroshko** [comment]
@Dara-K I think you can try uploading too big file, larger than 200Mb

**Comment by Dara-K** [comment]
I can see this working! I added some notes to the other ticket for fixing the formatting of the message but otherwise it's good. Let's close this! Thank you @igoroshko
