### ISSUE TITLE
[Mobile] Set initial value of sidebar navigation to current year

### ISSUE THREAD

**Issue by igoroshko** [topcoder-platform/timeline-wall-api#29]
The initial value on sidebar navigation should be set to current year:

![image](https://user-images.githubusercontent.com/15140568/205027699-501b988e-1a67-4416-9945-a62519c50a31.png)

**Comment by suppermancool** [comment]
@igoroshko done in https://github.com/topcoder-platform/community-app/pull/6741

**Comment by igoroshko** [comment]
@suppermancool great, thanks!

**Comment by Dara-K** [comment]
Looks good! Let's close this @igoroshko
