### ISSUE TITLE
Images look blurry in wall but clear when clicked on

### ISSUE THREAD

**Issue by jmpld40** [topcoder-platform/timeline-wall-api#8]
![Screen Shot 2022-11-08 at 11 25 58 AM](https://user-images.githubusercontent.com/40000534/200620611-e83c2e12-cdd5-45a7-9045-3b7b6517eb71.png)
![Screen Shot 2022-11-08 at 11 26 39 AM](https://user-images.githubusercontent.com/40000534/200620708-12d0f874-922d-402f-87b2-b532d956aa59.png)

**Comment by Dara-K** [comment]
This one looks good too - tested with same image on the test account.

Thank you! Please close this @igoroshko
